### ISSUE TITLE
500 When using ^ character.

### ISSUE THREAD

**Issue by pylover** [Carrene/restfulpy#122]
```python
Failure
Traceback (most recent call last):
  File "/opt/python3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python3.6/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/home/vahid/workspace/leo/leo/tests/test_icd_code.py", line 74, in test_user_icd_code
    self.request(As.user, 'GET', self.url, query_string=dict(id='^'), expected_status=400)
  File "/home/vahid/workspace/restfulpy/restfulpy/testing/testcases.py", line 154, in request
    **kwargs
  File "/home/vahid/workspace/restfulpy/restfulpy/testing/testcases.py", line 106, in request
    self.assertEqual(resp.status_code, expected_status)
  File "/opt/python3.6/lib/python3.6/unittest/case.py", line 821, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/python3.6/lib/python3.6/unittest/case.py", line 814, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 500 != 400



Ran 1 test in 21.443s

FAILED (failures=1)
```

**Comment by pylover** [comment]
It happens after the #114
