### ISSUE TITLE
Internal server error when posting on `/apiv1/sessions` (redis not installed)

### ISSUE THREAD

**Issue by EhsanMashhadi** [Carrene/restfulpy#128]
```
2017-11-15 16:21:57 - main - ERROR - Internal server error
Traceback (most recent call last):
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/application.py", line 65, in __call__
    response_body = self.__root__(*remaining_paths)
  File "/home/mysterious/workspaces/restfulpy/restfulpy/controllers.py", line 18, in __call__
    return super().__call__(*remaining_paths)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/controllers.py", line 59, in __call__
    return self._serve_handler(handler, *remaining_paths)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/controllers.py", line 30, in _serve_handler
    return handler(*remaining_paths)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/controllers.py", line 59, in __call__
    return self._serve_handler(handler, *remaining_paths)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/controllers.py", line 30, in _serve_handler
    return handler(*remaining_paths)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/decorators.py", line 36, in wrapper
    result = func(*args, **kwargs)
  File "/home/mysterious/workspaces/restfulpy/restfulpy/mockupservers/simple.py", line 80, in post
    principal = context.application.__authenticator__.login((email, password))
  File "/home/mysterious/workspaces/restfulpy/restfulpy/authentication.py", line 204, in login
    principal = super().login(credentials)
  File "/home/mysterious/workspaces/restfulpy/restfulpy/authentication.py", line 110, in login
    self.ok(principal)
  File "/home/mysterious/workspaces/restfulpy/restfulpy/authentication.py", line 286, in ok
    self.update_session_info(principal.session_id)
  File "/home/mysterious/workspaces/restfulpy/restfulpy/authentication.py", line 289, in update_session_info
    self.redis.set(self.get_session_info_key(session_id), ujson.dumps(self.extract_agent_info()))
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
ERROR:main:Internal server error
Traceback (most recent call last):
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/application.py", line 65, in __call__
    response_body = self.__root__(*remaining_paths)
  File "/home/mysterious/workspaces/restfulpy/restfulpy/controllers.py", line 18, in __call__
    return super().__call__(*remaining_paths)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/controllers.py", line 59, in __call__
    return self._serve_handler(handler, *remaining_paths)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/controllers.py", line 30, in _serve_handler
    return handler(*remaining_paths)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/controllers.py", line 59, in __call__
    return self._serve_handler(handler, *remaining_paths)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/controllers.py", line 30, in _serve_handler
    return handler(*remaining_paths)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/decorators.py", line 36, in wrapper
    result = func(*args, **kwargs)
  File "/home/mysterious/workspaces/restfulpy/restfulpy/mockupservers/simple.py", line 80, in post
    principal = context.application.__authenticator__.login((email, password))
  File "/home/mysterious/workspaces/restfulpy/restfulpy/authentication.py", line 204, in login
    principal = super().login(credentials)
  File "/home/mysterious/workspaces/restfulpy/restfulpy/authentication.py", line 110, in login
    self.ok(principal)
  File "/home/mysterious/workspaces/restfulpy/restfulpy/authentication.py", line 286, in ok
    self.update_session_info(principal.session_id)
  File "/home/mysterious/workspaces/restfulpy/restfulpy/authentication.py", line 289, in update_session_info
    self.redis.set(self.get_session_info_key(session_id), ujson.dumps(self.extract_agent_info()))
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/mysterious/.virtualenvs/restfulpy/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
127.0.0.1 - - [15/Nov/2017 16:21:57] "POST /sessions HTTP/1.1" 500 5338
```
```
Request{method=POST, url=http://localhost:8080/sessions, tag=null}
body {"email":"user1@example.com","password":"123456"}
```

**Comment by pylover** [comment]
You have to install the redis-server package.
