### ISSUE TITLE
Mockup server echo request error

### ISSUE THREAD

**Issue by mrastiak** [Carrene/restfulpy#156]
I get the following error when trying send this request:
`GET` `/echo?item=value1`
``` python
ERROR:main:Internal server error
Traceback (most recent call last):
  File "/home/armin/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/application.py", line 64, in __call__
    response_body = self.__root__(*remaining_paths)
  File "/home/armin/.virtualenvs/restfulpy/lib/python3.6/site-packages/restfulpy/controllers.py", line 18, in __call__
    return super().__call__(*remaining_paths)
  File "/home/armin/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/controllers.py", line 83, in __call__
    return self._serve_handler(handler, remaining_paths)
  File "/home/armin/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/controllers.py", line 78, in _serve_handler
    return handler(*remaining_paths, **kwargs)
  File "/home/armin/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/decorators.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/armin/.virtualenvs/restfulpy/lib/python3.6/site-packages/restfulpy/mockupservers/simple.py", line 144, in echo
    return {k: v for i in (context.form, context.query_string) for k, v in i.items()}
  File "/home/armin/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/contexts.py", line 184, in __getattr__
    return getattr(Context.get_current(), key)
  File "/home/armin/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/helpers.py", line 40, in __get__
    val = f(obj)
  File "/home/armin/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/contexts.py", line 115, in form
    content_type=self.request_content_type
  File "/home/armin/.virtualenvs/restfulpy/lib/python3.6/site-packages/nanohttp/helpers.py", line 133, in parse_any_form
    content_length = int(environ.get('CONTENT_LENGTH', 0))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by pylover** [comment]
It will be fixed in the next `nanohttp` release.

**Comment by mrastiak** [comment]
@pylover Thanks the issue is fixed.
